services:
  minio:
    container_name: minio
    image: "minio/minio:latest"
    command: server /data --console-address ":9001"
    volumes:
      - "minio_data:/data"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadmin"
      MINIO_DOMAIN: "localhost"
      MINIO_SERVER_URL: "http://localhost:9000"

  nbf-file-storage-service:
    container_name: nbf-file-storage-service
    image: acyushka/nbf-file-storage-service:latest
    ports:
      - "60005:60005"
    volumes:
      - ./config/local.yaml:/app/config/local.yaml:ro
    extra_hosts:
      - "localhost:host-gateway"
    depends_on:
      - minio

volumes:
  minio_data:
